In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("/content/eng_sentences.tsv", sep='\t')
df_raw.head()

   1276  eng                              Let's try something.
0  1277  eng                            I have to go to sleep.
1  1280  eng  Today is June 18th and it is Muiriel's birthday!
2  1282  eng                                Muiriel is 20 now.
3  1283  eng                        The password is "Muiriel".
4  1284  eng                              I will be back soon.

In [3]:
df_raw.shape

(1951597, 3)

In [4]:
# This code is generated by Claude to be honest
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r"[^a-z\s']", '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_raw["Let's try something."] = df_raw["Let's try something."].astype(str).apply(clean_text)
df_raw.head()

   1276  eng                           Let's try something.
0  1277  eng                          i have to go to sleep
1  1280  eng  today is june th and it is muiriel's birthday
2  1282  eng                                 muiriel is now
3  1283  eng                        the password is muiriel
4  1284  eng                            i will be back soon

In [5]:
# calculate our vocab size
sentences = []
for i in range(194379):
    sentences.append(df_raw["Let's try something."][i])

vocab = set()
for sentence in sentences:
    for word in sentence.split():
        vocab.add(word)

len(vocab)

31084

In [6]:
# Now we need to check number of occurences of each word
# This code is generated by Claude
from collections import Counter

all_words = [word for sentence in sentences for word in sentence.split()]
occ = Counter(all_words)

In [7]:
occ

Counter({'i': 37802,
         'have': 11268,
         'to': 51367,
         'go': 4192,
         'sleep': 420,
         'today': 1291,
         'is': 33995,
         'june': 92,
         'th': 165,
         'and': 12760,
         'it': 15132,
         "muiriel's": 4,
         'birthday': 242,
         'muiriel': 15,
         'now': 2132,
         'the': 85614,
         'password': 12,
         'will': 6860,
         'be': 8381,
         'back': 1513,
         'soon': 1083,
         "i'm": 3438,
         'at': 9411,
         'a': 41678,
         'loss': 159,
         'for': 14737,
         'words': 633,
         'this': 11583,
         'never': 1789,
         'going': 2137,
         'end': 581,
         'just': 2031,
         "don't": 4882,
         'know': 2915,
         'what': 5891,
         'say': 1527,
         'that': 14544,
         'was': 15677,
         'an': 4769,
         'evil': 100,
         'bunny': 2,
         'in': 25634,
         'mountains': 117,
         'recent': 73,
         'picture': 407,
         'if': 4241,
         'time': 4261,
         'education': 194,
         'world': 1120,
         'disappoints': 1,
         'me': 9408,
         "you're": 860,
         'better': 1535,
         'shape': 88,
         'than': 3007,
         'am': 2390,
         'you': 26229,
         'are': 9633,
         'my': 12555,
         'way': 1869,
         'cost': 293,
         'make': 2208,
         'day': 2326,
         'may': 1761,
         'give': 1335,
         'up': 4952,
         'nap': 28,
         'instead': 172,
         "it's": 3177,
         'because': 1452,
         'want': 2229,
         'alone': 489,
         "won't": 607,
         'happen': 219,
         'sometimes': 380,
         'he': 27775,
         'can': 5037,
         'strange': 318,
         'guy': 115,
         "i'll": 1553,
         'do': 6919,
         'best': 1034,
         'not': 8883,
         'disturb': 22,
         'your': 7392,
         'studying': 325,
         'only': 1834,
         'wonder': 353,
         'same': 703,
         'everyone': 564,
         'else': 246,
         'suppose': 84,
         'different': 353,
         'when': 4360,
         'think': 2230,
         'about': 3958,
         'over': 1834,
         'long': 1715,
         'term': 75,
         'miss': 251,
         'call': 888,
         'them': 1440,
         'tomorrow': 1231,
         'come': 2746,
         'always': 1797,
         'liked': 132,
         'mysterious': 20,
         'characters': 40,
         'more': 2847,
         'should': 2472,
         'told': 1007,
         'send': 257,
         'another': 728,
         'ticket': 201,
         'so': 3650,
         'impatient': 41,
         'with': 10308,
         "can't": 2150,
         'live': 1044,
         'kind': 785,
         'of': 28219,
         'life': 1519,
         'once': 1022,
         'wanted': 552,
         'astrophysicist': 2,
         'biology': 28,
         'last': 1950,
         'person': 738,
         'idea': 559,
         'thought': 647,
         'nuts': 24,
         "weren't": 66,
         'could': 2200,
         'trust': 180,
         'anyone': 283,
         'unfortunately': 63,
         'true': 668,
         'they': 5693,
         'too': 1954,
         'busy': 503,
         'fighting': 79,
         'against': 694,
         'each': 801,
         'other': 1480,
         'care': 565,
         'common': 206,
         'ideals': 17,
         'most': 1066,
         'people': 2900,
         'crazy': 112,
         'no': 4146,
         "that's": 707,
         'line': 256,
         "he's": 1134,
         'kicking': 8,
         'sure': 625,
         'then': 768,
         'there': 5350,
         'problem': 879,
         'oh': 207,
         "there's": 633,
         'butterfly': 28,
         'hurry': 246,
         "doesn't": 1613,
         'surprise': 146,
         'some': 2310,
         'reason': 338,
         'feel': 789,
         'alive': 169,
         'night': 1240,
         'depends': 120,
         'on': 11177,
         'context': 16,
         'freaking': 3,
         'kidding': 18,
         'stupidest': 2,
         'thing': 841,
         "i've": 1105,
         'ever': 775,
         'said': 1637,
         'lame': 6,
         'cool': 93,
         'grow': 147,
         'king': 170,
         'america': 424,
         'lovely': 82,
         'place': 755,
         'here': 2217,
         'earn': 45,
         'money': 2049,
         'fat': 105,
         'gonna': 27,
         'shoot': 33,
         'him': 7012,
         'real': 256,
         'fish': 349,
         'mere': 48,
         'plushy': 1,
         'saying': 314,
         'probably': 176,
         'influenced': 17,
         'their': 2301,
         'decision': 184,
         'wondered': 50,
         "it'd": 15,
         'like': 5077,
         'siblings': 9,
         'would': 3339,
         'take': 2367,
         'forever': 75,
         'explain': 138,
         'everything': 693,
         'girl': 791,
         'help': 1579,
         'showing': 45,
         'emotions': 26,
         'word': 574,
         "i'd": 869,
         'find': 858,
         'substitute': 19,
         'something': 1047,
         'program': 111,
         'intend': 64,
         'selfish': 34,
         "let's": 964,
         'consider': 141,
         'worst': 85,
         'how': 3345,
         'many': 2266,
         'close': 303,
         'friends': 824,
         'antisocial': 4,
         'but': 4395,
         'mean': 290,
         'talk': 646,
         'has': 6053,
         'been': 2886,
         'impolite': 14,
         'one': 3547,
         'unhappy': 69,
         "wouldn't": 306,
         'kill': 128,
         'myself': 477,
         'high': 643,
         'school': 1799,
         'got': 2149,
         'every': 1588,
         'morning': 987,
         'woke': 57,
         'sad': 183,
         'somewhat': 25,
         'explained': 100,
         'learn': 466,
         'new': 2293,
         'things': 876,
         'write': 552,
         'daily': 86,
         'marshmallow': 1,
         'trang': 12,
         'order': 503,
         'risks': 17,
         'who': 2345,
         'afraid': 472,
         'others': 517,
         'why': 1174,
         'ask': 555,
         'artist': 80,
         'had': 5201,
         'knack': 8,
         'tell': 1387,
         'her': 8264,
         'simple': 124,
         'anymore': 126,
         'flawed': 1,
         'these': 1237,
         'flaws': 3,
         'easily': 283,
         'fixed': 105,
         'whenever': 153,
         'expensive': 269,
         'did': 2519,
         'stay': 630,
         'maybe': 112,
         'exactly': 129,
         'innocence': 58,
         'beautiful': 722,
         'humans': 36,
         'were': 3608,
         'meant': 98,
         'lose': 229,
         'ideas': 183,
         'even': 979,
         'though': 329,
         'bit': 288,
         'extreme': 30,
         'theory': 163,
         'intriguing': 3,
         'intentionally': 9,
         'hide': 56,
         'good': 3358,
         'looks': 623,
         'account': 292,
         'forums': 2,
         'point': 399,
         'story': 593,
         'really': 1130,
         "didn't": 1814,
         'where': 1478,
         'came': 1502,
         'from': 5578,
         'living': 496,
         'important': 555,
         "she's": 536,
         'asking': 100,
         'possible': 359,
         'running': 286,
         'away': 1146,
         "life's": 12,
         'problems': 253,
         'look': 1224,
         'lyrics': 6,
         'much': 2377,
         'see': 2350,
         'physics': 59,
         'teacher': 976,
         'skip': 22,
         'classes': 75,
         'wish': 470,
         'japan': 1043,
         'hate': 129,
         'lot': 1338,
         'bed': 595,
         'after': 2034,
         'left': 1272,
         'realized': 81,
         'forgot': 150,
         'backpack': 6,
         'house': 1809,
         'anything': 949,
         'freeze': 18,
         'next': 1287,
         'week': 925,
         'apologized': 35,
         'still': 983,
         'furious': 17,
         'police': 488,
         'get': 3197,
         'bullets': 7,
         'thanks': 194,
         'having': 675,
         'idiot': 42,
         "wasn't": 325,
         'intention': 52,
         'explanation': 103,
         'theoretically': 4,
         'doing': 552,
         'math': 107,
         'simply': 78,
         'almost': 448,
         'scared': 64,
         'online': 45,
         'whole': 394,
         'computer': 294,
         'useful': 142,
         'freedom': 99,
         'uh': 11,
         'weird': 22,
         'scare': 12,
         'dreamt': 27,
         'few': 798,
         'weeks': 144,
         'ago': 499,
         'expect': 171,
         'schools': 50,
         'understand': 595,
         'mathematicians': 7,
         'express': 114,
         'themselves': 180,
         'explicitly': 1,
         'stupid': 119,
         'need': 1173,
         'silly': 61,
         'question': 514,
         'demonstrate': 8,
         'since': 722,
         'obvious': 51,
         'someday': 58,
         'viagra': 2,
         'wikipedia': 7,
         'phrased': 1,
         'found': 869,
         'solution': 68,
         'fast': 414,
         'right': 1301,
         'seems': 655,
         'interesting': 371,
         'except': 149,
         'candlelight': 2,
         'answer': 584,
         'boyfriend': 79,
         'bad': 846,
         'weight': 192,
         'class': 604,
         'or': 2060,
         'play': 970,
         'sudoku': 2,
         'continuing': 9,
         'bother': 66,
         'wait': 420,
         'love': 1090,
         'curious': 43,
         'congratulations': 20,
         'visit': 388,
         'us': 2186,
         'possibility': 53,
         'unlikely': 89,
         "shouldn't": 264,
         'logged': 3,
         'off': 1865,
         'inevitable': 18,
         'france': 187,
         'chemistry': 39,
         'guess': 128,
         'happens': 87,
         "you'll": 491,
         'papers': 109,
         'options': 13,
         'traveller': 3,
         'nothing': 1305,
         'either': 241,
         'strengths': 1,
         'weaknesses': 8,
         'seriously': 103,
         'episode': 8,
         'made': 2163,
         'cry': 164,
         'while': 949,
         'laughing': 106,
         'shows': 91,
         'robot': 40,
         'robots': 18,
         'dream': 249,
         'underestimate': 9,
         'power': 191,
         'mom': 74,
         'speak': 1103,
         'english': 1716,
         'very': 3732,
         'well': 1978,
         'french': 571,
         'enough': 763,
         'wondering': 54,
         'show': 478,
         'therein': 3,
         'lies': 139,
         'food': 751,
         'outer': 7,
         'space': 120,
         'all': 5467,
         'wants': 430,
         'meet': 593,
         'famous': 331,
         'sorry': 449,
         "haven't": 333,
         'done': 589,
         'utterly': 17,
         'despise': 17,
         'formal': 25,
         'writing': 243,
         'foreign': 323,
         'intrigue': 2,
         'whatever': 217,
         'she': 12899,
         'says': 437,
         'keeps': 161,
         'late': 951,
         "you'd": 209,
         'surprised': 286,
         "who'd": 9,
         'travel': 253,
         'hard': 1285,
         'harder': 152,
         'bearing': 19,
         'unbearable': 7,
         'stop': 567,
         'making': 421,
         'uncomfortable': 22,
         'truth': 519,
         'land': 180,
         'moon': 191,
         'japanese': 844,
         'pun': 3,
         'nobody': 287,
         'understands': 30,
         'learned': 212,
         'without': 1196,
         'useless': 48,
         'keep': 1021,
         'thinking': 278,
         'any': 1934,
         'mind': 827,
         'days': 935,
         'check': 194,
         'email': 82,
         'behind': 385,
         'we': 9235,
         'priorities': 4,
         'use': 950,
         'pretending': 13,
         'believe': 615,
         'work': 2370,
         'dumb': 23,
         'trying': 295,
         'seeing': 250,
         'as': 8055,
         'normal': 61,
         'referring': 12,
         'eternity': 12,
         'before': 1776,
         'grades': 35,
         'certain': 263,
         'decided': 438,
         'rolling': 23,
         'stone': 130,
         'gathers': 5,
         'moss': 4,
         'proverb': 23,
         'drink': 499,
         'mother': 1349,
         'weather': 619,
         "what's": 724,
         'matter': 780,
         'asked': 996,
         'little': 1480,
         'white': 422,
         'rabbit': 45,
         'cave': 21,
         'must': 2214,
         'together': 389,
         'brothers': 119,
         'perish': 15,
         'fools': 22,
         "how's": 52,
         'working': 465,
         'heights': 11,
         'coward': 36,
         'looking': 617,
         'exclaimed': 13,
         'pretty': 291,
         'hiroshi': 15,
         'communication': 53,
         'complex': 49,
         'phone': 360,
         'ringing': 27,
         'nice': 479,
         'willie': 5,
         'answered': 104,
         'thank': 276,
         'helping': 80,
         'mention': 90,
         'run': 561,
         'wind': 267,
         'likes': 455,
         'music': 589,
         'please': 2698,
         'let': 988,
         'happiness': 181,
         'awaiting': 5,
         'sort': 131,
         'decide': 111,
         'whether': 473,
         'begin': 169,
         'until': 624,
         'eightthirty': 10,
         'boat': 169,
         'far': 770,
         'playing': 450,
         'cards': 103,
         'met': 665,
         'somewhere': 103,
         'student': 444,
         'such': 1368,
         'allen': 7,
         'poet': 115,
         'archer': 1,
         'killed': 285,
         'deer': 31,
         'communism': 19,
         'reached': 192,
         'lifetime': 24,
         'rye': 3,
         'called': 722,
         'grain': 28,
         'poverty': 74,
         "'s": 12,
         'finns': 3,
         'cited': 4,
         'least': 287,
         'healthy': 114,
         'diets': 2,
         'mistake': 335,
         'correct': 153,
         'deck': 12,
         'oaken': 1,
         'table': 453,
         'germans': 26,
         'crafty': 2,
         'eat': 939,
         'die': 261,
         'spell': 50,
         'home': 1768,
         'ten': 828,
         'years': 1464,
         "aren't": 248,
         'million': 155,
         'lost': 877,
         'lives': 465,
         'war': 556,
         'rare': 79,
         'ninety': 16,
         'first': 1305,
         'outline': 5,
         'website': 42,
         'democracy': 61,
         'form': 171,
         'government': 339,
         'tried': 606,
         'beginning': 139,
         'photo': 61,
         'passport': 60,
         'holiday': 143,
         'commissioner': 2,
         'pants': 39,
         'around': 953,
         'naturally': 38,
         'became': 412,
         'nervous': 90,
         'train': 973,
         'station': 716,
         'saw': 909,
         'man': 2512,
         'angel': 25,
         'madrid': 10,
         'quite': 610,
         "isn't": 770,
         'lucky': 88,
         'bite': 69,
         'eggs': 140,
         'round': 158,
         'trip': 350,
         'oneway': 4,
         'pity': 72,
         'somebody': 136,
         'dies': 21,
         'speechless': 9,
         'damn': 32,
         'pull': 66,
         'into': 2177,
         'washing': 93,
         'wash': 169,
         'wearing': 154,
         'open': 519,
         'stops': 51,
         'those': 840,
         'glass': 210,
         'houses': 140,
         'throw': 104,
         'stones': 28,
         'blind': 89,
         'complicated': 39,
         'answers': 61,
         'raise': 110,
         'questions': 239,
         'doubts': 42,
         'oneself': 17,
         'sign': 185,
         'intelligence': 45,
         'poor': 467,
         'known': 363,
         'does': 1344,
         'souvenir': 8,
         'united': 272,
         'states': 277,
         'excuse': 194,
         'allow': 108,
         'out': 4744,
         'three': 1281,
         'errors': 45,
         'above': 282,
         'article': 82,
         'difficult': 620,
         'conversation': 122,
         'someone': 428,
         'yes': 277,
         'italian': 76,
         'noise': 253,
         'stared': 52,
         'typewriter': 26,
         'hamlet': 23,
         'written': 282,
         'inquired': 20,
         'master': 121,
         'impossible': 253,
         'spend': 258,
         'rest': 289,
         'regretting': 5,
         'fun': 250,
         'change': 493,
         'guessed': 19,
         'imagination': 45,
         'affects': 19,
         'aspect': 17,
         'our': 3162,
         'forget': 296,
         'rather': 380,
         'unexpected': 48,
         'tv': 445,
         "couldn't": 808,
         'achieved': 59,
         'effort': 163,
         'drift': 6,
         'through': 821,
         'purpose': 152,
         'totally': 45,
         'pointless': 8,
         'changes': 96,
         'exams': 46,
         'ruining': 5,
         'condom': 7,
         'tells': 73,
         'walk': 655,
         'minutes': 442,
         'took': 1245,
         'two': 2016,
         'hours': 552,
         'translate': 82,
         'pages': 53,
         'already': 478,
         'eleven': 61,
         'ms': 23,
         'brown': 174,
         'orange': 64,
         'juice': 58,
         'mike': 130,
         'ah': 44,
         'interjection': 3,
         'mandatory': 5,
         'character': 130,
         'schooling': 5,
         'rarely': 59,
         'analyzed': 7,
         'multitude': 3,
         'works': 296,
         'dedicated': 22,
         'study': 810,
         'various': 113,
         'ways': 112,
         'develop': 43,
         'within': 184,
         'children': 1249,
         'desire': 77,
         'suck': 7,
         'dude': 7,
         'bone': 47,
         'pick': 163,
         'paris': 243,
         'city': 673,
         'hey': 69,
         'pride': 73,
         'friend': 715,
         'rachel': 3,
         'went': 1951,
         'increased': 66,
         'drastically': 5,
         'which': 1284,
         'invented': 68,
         'universe': 70,
         'infinite': 25,
         'perfect': 120,
         'lacked': 8,
         'defect': 11,
         'yet': 572,
         'contrary': 61,
         'den': 2,
         'crazies': 3,
         'opened': 171,
         'eyes': 506,
         'by': 5741,
         'side': 325,
         "everything's": 8,
         'fine': 368,
         'name': 780,
         'jack': 141,
         "we're": 334,
         'meeting': 682,
         'shopping': 196,
         'hour': 360,
         'mine': 357,
         'dance': 122,
         'italy': 92,
         'country': 809,
         'fault': 146,
         'dial': 14,
         'telephone': 303,
         'youth': 119,
         'hostel': 3,
         'near': 359,
         'showers': 12,
         'mouth': 138,
         'wallet': 94,
         'wasted': 35,
         'plans': 161,
         'wanting': 22,
         'sexy': 8,
         'pass': 347,
         'salt': 126,
         'bored': 67,
         'eating': 325,
         'chocolate': 84,
         'yourself': 492,
         'appetite': 46,
         'hit': 291,
         'disneyland': 17,
         'family': 700,
         'parents': 640,
         'arguing': 38,
         'annoying': 24,
         'put': 1471,
         'sunscreen': 4,
         'complaining': 77,
         'sunburn': 10,
         'calm': 92,
         'spiders': 17,
         "they're": 204,
         'freak': 1,
         'cleaning': 59,
         'headache': 89,
         'hot': 445,
         'cook': 162,
         'egg': 57,
         'hood': 10,
         'car': 1705,
         'red': 421,
         'fridge': 12,
         'hated': 30,
         'loved': 167,
         'lonely': 71,
         'saddle': 4,
         'horse': 211,
         'died': 424,
         'mathematics': 105,

In [8]:
# Generated by Claude
sorted_rare = sorted(
    ((w, c) for w, c in occ.items() if c <= 2),
    key=lambda x: x[1]
)

In [9]:
# Generated by Claude
rare_words = {w for w, c in sorted_rare}
vocab = vocab - rare_words

len(vocab)

14086

In [10]:
# This code generally generated by Andrej Karpathy
special_tokens = ["<pad>", "<unk>"]
vocab_full = special_tokens + [w for w in vocab if w not in special_tokens]

stoi = {word: i for i, word in enumerate(vocab_full)}
itos = {i: word for i, word in enumerate(vocab_full)}

In [11]:
stoi

{'<pad>': 0,
 '<unk>': 1,
 'astonishment': 2,
 'bathed': 3,
 'fourletter': 4,
 'boring': 5,
 'pleaded': 6,
 'granddaughter': 7,
 'decreasing': 8,
 'unturned': 9,
 'stronger': 10,
 'spider': 11,
 'crammed': 12,
 "kelly's": 13,
 'retorted': 14,
 'hitherto': 15,
 'politically': 16,
 'tuning': 17,
 'freed': 18,
 'runny': 19,
 'okinawa': 20,
 'expecting': 21,
 'constantly': 22,
 'aback': 23,
 'james': 24,
 'okay': 25,
 'jig': 26,
 'tutor': 27,
 'lighted': 28,
 'vietnamese': 29,
 'planned': 30,
 "what's": 31,
 'empire': 32,
 'newspaperman': 33,
 'macedonian': 34,
 'vocal': 35,
 'village': 36,
 'aftermath': 37,
 "someone's": 38,
 'stale': 39,
 'charged': 40,
 'count': 41,
 'links': 42,
 'bee': 43,
 'outside': 44,
 'director': 45,
 'inevitably': 46,
 'free': 47,
 'helmet': 48,
 'symbols': 49,
 'absolved': 50,
 'cheering': 51,
 'nepal': 52,
 'zuckerberg': 53,
 'raise': 54,
 'surgery': 55,
 'twohour': 56,
 'replacing': 57,
 'ridden': 58,
 'strap': 59,
 'premises': 60,
 'extension': 61,
 'appointed': 62,
 'tarts': 63,
 'bring': 64,
 'heating': 65,
 'brain': 66,
 'managerial': 67,
 'default': 68,
 'exhibits': 69,
 'openly': 70,
 'squish': 71,
 'dreary': 72,
 'show': 73,
 'careful': 74,
 'nave': 75,
 'screwed': 76,
 'shop': 77,
 'trusted': 78,
 'tortoise': 79,
 'serves': 80,
 'at': 81,
 'nightfall': 82,
 'sunny': 83,
 'impose': 84,
 'impact': 85,
 'owe': 86,
 'manage': 87,
 'commas': 88,
 'fluttered': 89,
 'sally': 90,
 'politician': 91,
 'whispering': 92,
 'beds': 93,
 'romanian': 94,
 'forming': 95,
 't': 96,
 'admitted': 97,
 'merrily': 98,
 'specimen': 99,
 'benefactor': 100,
 'sheila': 101,
 'pear': 102,
 'bruises': 103,
 'sidewalk': 104,
 'disapproved': 105,
 'spent': 106,
 'tempura': 107,
 'spam': 108,
 "shakespeare's": 109,
 'newsstand': 110,
 'paula': 111,
 'slapped': 112,
 'ironic': 113,
 'visited': 114,
 'jefferson': 115,
 'exploited': 116,
 'operates': 117,
 'painfully': 118,
 'eitheror': 119,
 'overhead': 120,
 'gin': 121,
 'suppress': 122,
 'shadow': 123,
 'polk': 124,
 'iranians': 125,
 'swiftly': 126,
 'fetch': 127,
 'temperatures': 128,
 'fitting': 129,
 'peck': 130,
 'rose': 131,
 'easily': 132,
 'diana': 133,
 'travelers': 134,
 'finnish': 135,
 'unbearably': 136,
 'vaguely': 137,
 'help': 138,
 'resting': 139,
 'crowns': 140,
 'concerning': 141,
 'deepseated': 142,
 'cheeks': 143,
 'women': 144,
 'words': 145,
 'manager': 146,
 'district': 147,
 'endeavor': 148,
 'idiots': 149,
 'popular': 150,
 'beard': 151,
 'cancellation': 152,
 'schools': 153,
 'knot': 154,
 'itchy': 155,
 'telling': 156,
 'maid': 157,
 'shuddered': 158,
 'misunderstand': 159,
 'deathly': 160,
 'boys': 161,
 'monkey': 162,
 'precise': 163,
 'seventeenth': 164,
 'clues': 165,
 'peacefully': 166,
 'wreckage': 167,
 'garage': 168,
 'obedience': 169,
 "else's": 170,
 'resumed': 171,
 'disappearance': 172,
 'reduction': 173,
 'sings': 174,
 'proceeding': 175,
 'card': 176,
 'weve': 177,
 'molecule': 178,
 'membership': 179,
 'afterward': 180,
 'counts': 181,
 'affair': 182,
 'clip': 183,
 'inconvenient': 184,
 'inca': 185,
 'reflect': 186,
 'flats': 187,
 'shampoo': 188,
 'hint': 189,
 'wig': 190,
 'girls': 191,
 'suits': 192,
 'kyiv': 193,
 'cozy': 194,
 'coldest': 195,
 'references': 196,
 'returns': 197,
 'participants': 198,
 'eurovision': 199,
 'pocket': 200,
 'sioux': 201,
 'hamburger': 202,
 'belarus': 203,
 'atoms': 204,
 'affairs': 205,
 'persontoperson': 206,
 'childishness': 207,
 'fainted': 208,
 "mcdonald's": 209,
 'scare': 210,
 'problems': 211,
 'yelled': 212,
 'suffice': 213,
 "hour's": 214,
 'cabinet': 215,
 'remembrance': 216,
 'statues': 217,
 'necktie': 218,
 'asians': 219,
 'contradictions': 220,
 'tune': 221,
 'wider': 222,
 'job': 223,
 'style': 224,
 'specify': 225,
 'falls': 226,
 'bank': 227,
 'vegas': 228,
 'charmed': 229,
 'balloon': 230,
 'identical': 231,
 'worldfamous': 232,
 'descends': 233,
 'lecturer': 234,
 'application': 235,
 'millionaires': 236,
 'educate': 237,
 "china's": 238,
 'johnston': 239,
 'enlightenment': 240,
 'suggestion': 241,
 'silence': 242,
 'fishing': 243,
 'suicide': 244,
 'commons': 245,
 'wills': 246,
 'duties': 247,
 'mary': 248,
 'netherlands': 249,
 'shining': 250,
 'unions': 251,
 'groupings': 252,
 'springtime': 253,
 'gymnastics': 254,
 'samantha': 255,
 'presented': 256,
 'ram': 257,
 'unfounded': 258,
 'overall': 259,
 'motorcycles': 260,
 'included': 261,
 'thicker': 262,
 'made': 263,
 'slaughter': 264,
 'safety': 265,
 'collapse': 266,
 'carol': 267,
 'exquisite': 268,
 "here's": 269,
 'witches': 270,
 'repairman': 271,
 'cottoned': 272,
 'laughing': 273,
 'extinction': 274,
 'laura': 275,
 'whether': 276,
 'coolidge': 277,
 'objected': 278,
 'taxed': 279,
 'aims': 280,
 'strange': 281,
 'locks': 282,
 'meadow': 283,
 'oedipus': 284,
 'mineral': 285,
 'pennies': 286,
 'stranded': 287,
 'umbrellas': 288,
 'questionable': 289,
 'day': 290,
 'publicly': 291,
 'pet': 292,
 'confess': 293,
 'rapid': 294,
 'checkup': 295,
 'pimples': 296,
 'pickpockets': 297,
 'wilderness': 298,
 'nonstop': 299,
 'vicious': 300,
 'glasses': 301,
 'emissions': 302,
 'fairly': 303,
 'reads': 304,
 'wage': 305,
 'combine': 306,
 'via': 307,
 'man': 308,
 'coral': 309,
 'just': 310,
 'agriculture': 311,
 'protesting': 312,
 'restrained': 313,
 'spaces': 314,
 'lukewarm': 315,
 'butts': 316,
 'stocking': 317,
 'unexpected': 318,
 'dead': 319,
 'observe': 320,
 'spoiled': 321,
 'organize': 322,
 'scold': 323,
 'defendant': 324,
 'beers': 325,
 'destination': 326,
 'partly': 327,
 'vet': 328,
 'doubt': 329,
 'buck': 330,
 'sashimi': 331,
 'uphill': 332,
 'idly': 333,
 'seasoned': 334,
 'completely': 335,
 'arrange': 336,
 'overcast': 337,
 'handed': 338,
 'viewed': 339,
 'romantic': 340,
 'hug': 341,
 'twin': 342,
 'designed': 343,
 'contemplated': 344,
 'fortyfive': 345,
 'operated': 346,
 'couples': 347,
 'batman': 348,
 'institution': 349,
 'ties': 350,
 'ineffective': 351,
 'nose': 352,
 'shiver': 353,
 'jumbo': 354,
 'age': 355,
 'records': 356,
 'atlantic': 357,
 'traitor': 358,
 'conceal': 359,
 'backyard': 360,
 'situated': 361,
 'sneeze': 362,
 'coercion': 363,
 'hedgehogs': 364,
 'loss': 365,
 'develops': 366,
 'dreaming': 367,
 'appendicitis': 368,
 'stripped': 369,
 'seniors': 370,
 'deny': 371,
 'sluggish': 372,
 'stir': 373,
 'decisions': 374,
 'solitary': 375,
 'scabs': 376,
 'cabbage': 377,
 'excellence': 378,
 'treats': 379,
 'phoning': 380,
 'batter': 381,
 'quarrels': 382,
 'mistake': 383,
 'fractured': 384,
 'borders': 385,
 'robe': 386,
 'predicate': 387,
 'voyage': 388,
 'triumph': 389,
 'companies': 390,
 'regulated': 391,
 'alain': 392,
 'lifting': 393,
 'capabilities': 394,
 'assuming': 395,
 'repented': 396,
 'deteriorated': 397,
 'defied': 398,
 'contentment': 399,
 'reputation': 400,
 'burdened': 401,
 'spaniard': 402,
 'geneva': 403,
 'discord': 404,
 'meaningless': 405,
 "how's": 406,
 "needn't": 407,
 'pistol': 408,
 "lincoln's": 409,
 'week': 410,
 'bunch': 411,
 'companion': 412,
 'skim': 413,
 'regulations': 414,
 'tin': 415,
 'vulnerability': 416,
 'abstract': 417,
 'prison': 418,
 'disks': 419,
 'yen': 420,
 'streets': 421,
 'nest': 422,
 'named': 423,
 'microphone': 424,
 'barn': 425,
 'excitement': 426,
 'luckily': 427,
 'acknowledge': 428,
 'description': 429,
 'relaxing': 430,
 'backgrounds': 431,
 'revealed': 432,
 'build': 433,
 'applying': 434,
 'beyond': 435,
 'proof': 436,
 'forbids': 437,
 'apprehension': 438,
 'patent': 439,
 'sufferings': 440,
 'beans': 441,
 'beg': 442,
 'bread': 443,
 'allowing': 444,
 'anniversary': 445,
 'swept': 446,
 'cloned': 447,
 'marie': 448,
 "team's": 449,
 'ulcer': 450,
 'circle': 451,
 'brings': 452,
 'centre': 453,
 'lions': 454,
 'barbarians': 455,
 'preposition': 456,
 'tricks': 457,
 'proposal': 458,
 'volunteers': 459,
 'gig': 460,
 'complaining': 461,
 'sympathized': 462,
 'camel': 463,
 'kangaroo': 464,
 'fair': 465,
 'handled': 466,
 'er': 467,
 'bachelors': 468,
 'feminism': 469,
 'kites': 470,
 'version': 471,
 'yukiko': 472,
 'must': 473,
 'inexperienced': 474,
 'cement': 475,
 'down': 476,
 'bobbed': 477,
 'beads': 478,
 'amber': 479,
 'ensued': 480,
 'robot': 481,
 'zen': 482,
 'hasten': 483,
 'skied': 484,
 'ale': 485,
 'optimistic': 486,
 'commander': 487,
 'mt': 488,
 'flow': 489,
 'collision': 490,
 'entries': 491,
 'crosslegged': 492,
 'mighty': 493,
 'weed': 494,
 'jumps': 495,
 'prime': 496,
 'recovered': 497,
 'skis': 498,
 'toaster': 499,
 "bob's": 500,
 "neighbor's": 501,
 "kid's": 502,
 'ban': 503,
 'prefectural': 504,
 "son's": 505,
 'feminine': 506,
 'civilized': 507,
 'worthwhile': 508,
 'sophisticated': 509,
 'mario': 510,
 'rubs': 511,
 'sincerity': 512,
 'browser': 513,
 'effectiveness': 514,
 'spoil': 515,
 'upon': 516,
 'salad': 517,
 'acquitted': 518,
 'advice': 519,
 'jams': 520,
 'coldly': 521,
 'physical': 522,
 'deliver': 523,
 'intervene': 524,
 'ashore': 525,
 'displays': 526,
 'guaranteed': 527,
 'affinity': 528,
 'miles': 529,
 'disassociate': 530,
 'rare': 531,
 'sector': 532,
 'retreated': 533,
 'tremendously': 534,
 'sizes': 535,
 'pen': 536,
 'smooth': 537,
 'daughters': 538,
 'musician': 539,
 'chuckled': 540,
 'accuse': 541,
 'nearest': 542,
 'preoccupied': 543,
 'lake': 544,
 'mushroom': 545,
 'brooding': 546,
 'artistic': 547,
 'selfevident': 548,
 'folder': 549,
 'survived': 550,
 'santa': 551,
 'equilibrium': 552,
 'nursery': 553,
 'noodles': 554,
 'hectic': 555,
 'disputed': 556,
 'stepmother': 557,
 'hospitality': 558,
 'beginners': 559,
 'pianist': 560,
 'importation': 561,
 'bus': 562,
 'depending': 563,
 'substantial': 564,
 'queue': 565,
 'preceded': 566,
 'milk': 567,
 'surprised': 568,
 'arts': 569,
 'fiddle': 570,
 'before': 571,
 'copied': 572,
 'irregular': 573,
 'driver': 574,
 'council': 575,
 'reasons': 576,
 'invoice': 577,
 'salty': 578,
 'floored': 579,
 'medication': 580,
 'kaisha': 581,
 'dictated': 582,
 'diagnosed': 583,
 "somebody's": 584,
 'sundays': 585,
 'aid': 586,
 'similarly': 587,
 'concern': 588,
 'results': 589,
 'nazi': 590,
 'hurricanes': 591,
 'studying': 592,
 'followers': 593,
 'extremes': 594,
 'tutorial': 595,
 'broth': 596,
 'innocence': 597,
 'rite': 598,
 'hideous': 599,
 'allergies': 600,
 "rain's": 601,
 'dreamt': 602,
 'cuban': 603,
 'sneaked': 604,
 'note': 605,
 'masterpieces': 606,
 'winning': 607,
 'designs': 608,
 'chew': 609,
 'prior': 610,
 'sweetest': 611,
 'fixed': 612,
 'murderer': 613,
 "she'd": 614,
 'iphone': 615,
 'naturally': 616,
 'staring': 617,
 'refugees': 618,
 'bloomer': 619,
 'sir': 620,
 'cracked': 621,
 'twentyeight': 622,
 'underwater': 623,
 'mango': 624,
 'discussing': 625,
 'disadvantage': 626,
 'starvation': 627,
 "party's": 628,
 'brought': 629,
 'impress': 630,
 'captive': 631,
 'congratulations': 632,
 'long': 633,
 'incumbent': 634,
 'tetanus': 635,
 'goldfish': 636,
 'roasted': 637,
 "hairdresser's": 638,
 'stoop': 639,
 "tanaka's": 640,
 'signing': 641,
 'images': 642,
 'discouraged': 643,
 'amazement': 644,
 'biased': 645,
 'steaks': 646,
 'involves': 647,
 'drill': 648,
 "kate's": 649,
 'sufficiently': 650,
 'serving': 651,
 'lemonade': 652,
 'uncertainty': 653,
 'cheerfully': 654,
 'cracker': 655,
 'she': 656,
 'beverage': 657,
 'preparing': 658,
 'contented': 659,
 'thai': 660,
 'starved': 661,
 'mob': 662,
 'revolutionary': 663,
 'hikari': 664,
 'passport': 665,
 'seafood': 666,
 'genius': 667,
 'wipe': 668,
 'years': 669,
 'totalled': 670,
 'valencia': 671,
 'bark': 672,
 'extract': 673,
 'province': 674,
 'bach': 675,
 'lone': 676,
 'dairy': 677,
 'coloured': 678,
 "uncle's": 679,
 'life': 680,
 'ascertain': 681,
 'dick': 682,
 'shovel': 683,
 'shares': 684,
 'plainer': 685,
 'uphold': 686,
 'asylum': 687,
 'block': 688,
 'medicine': 689,
 'left': 690,
 'judo': 691,
 'wash': 692,
 'sculptor': 693,
 'feeder': 694,
 'clearing': 695,
 'prescription': 696,
 'whoa': 697,
 'guilty': 698,
 'mortal': 699,
 'scruple': 700,
 'introduce': 701,
 'led': 702,
 'boiled': 703,
 'booth': 704,
 'blood': 705,
 'samurai': 706,
 'gall': 707,
 'richer': 708,
 'signatures': 709,
 'errand': 710,
 'incidentally': 711,
 'fuck': 712,
 'leopard': 713,
 'whole': 714,
 'robbery': 715,
 'takada': 716,
 'blot': 717,
 'desirable': 718,
 'excluded': 719,
 'tide': 720,
 'newscaster': 721,
 'censorship': 722,
 'vigor': 723,
 'maintenance': 724,
 'seriously': 725,
 'undertake': 726,
 'transformed': 727,
 'demons': 728,
 'store': 729,
 'anthony': 730,
 'deeply': 731,
 'ride': 732,
 'require': 733,
 'passive': 734,
 'prospect': 735,
 'wrote': 736,
 'truly': 737,
 "god's": 738,
 'donate': 739,
 'guinea': 740,
 'runaway': 741,
 'diabetes': 742,
 'pit': 743,
 'romans': 744,
 'oscar': 745,
 'labeled': 746,
 'oversleep': 747,
 'cradle': 748,
 'scorpion': 749,
 'bugging': 750,
 'tool': 751,
 'fourteen': 752,
 'shoes': 753,
 'smelled': 754,
 'watching': 755,
 'serve': 756,
 'elephants': 757,
 'tax': 758,
 'presence': 759,
 'blouse': 760,
 'analysis': 761,
 'ropes': 762,
 'revision': 763,
 'errands': 764,
 'heard': 765,
 'lung': 766,
 'brightening': 767,
 'tying': 768,
 'manchester': 769,
 'hardness': 770,
 'signature': 771,
 'publication': 772,
 'pub': 773,
 'contents': 774,
 'magician': 775,
 'inspiration': 776,
 'consumers': 777,
 'disabled': 778,
 'gaze': 779,
 'dream': 780,
 'handkerchief': 781,
 'learn': 782,
 'cigarette': 783,
 'smartest': 784,
 'simon': 785,
 'windshield': 786,
 'greed': 787,
 'languages': 788,
 'brush': 789,
 'strong': 790,
 'pregnancy': 791,
 'failures': 792,
 'thales': 793,
 'witnessed': 794,
 'methodology': 795,
 'shanghainese': 796,
 'dependence': 797,
 'father': 798,
 'republics': 799,
 'traded': 800,
 'mouse': 801,
 'festivals': 802,
 'z': 803,
 'wound': 804,
 'pip': 805,
 'details': 806,
 'kick': 807,
 'robbed': 808,
 'tempting': 809,
 'mechanic': 810,
 'recollection': 811,
 'meditate': 812,
 'likes': 813,
 'gifted': 814,
 'filling': 815,
 'regretfully': 816,
 'overpriced': 817,
 'suzuki': 818,
 'raincoat': 819,
 'wearing': 820,
 'mrs': 821,
 'bound': 822,
 'skip': 823,
 'tunnel': 824,
 'utility': 825,
 'persists': 826,
 'marriages': 827,
 'remote': 828,
 'babies': 829,
 'spite': 830,
 'mathematics': 831,
 'complex': 832,
 'sample': 833,
 'snowfall': 834,
 'kato': 835,
 'shaves': 836,
 "a's": 837,
 'look': 838,
 'cart': 839,
 'facility': 840,
 'unsuccessful': 841,
 'bounced': 842,
 'compelled': 843,
 'sayings': 844,
 'goodnatured': 845,
 "stone's": 846,
 'blossoms': 847,
 'inevitable': 848,
 'confide': 849,
 'individual': 850,
 'lyle': 851,
 'sting': 852,
 'crowned': 853,
 'accordance': 854,
 'divorcing': 855,
 'hindus': 856,
 'bells': 857,
 'jones': 858,
 'coup': 859,
 "lady's": 860,
 'damage': 861,
 'phoned': 862,
 'read': 863,
 'checking': 864,
 'hayashi': 865,
 'pitched': 866,
 'approximate': 867,
 'fading': 868,
 'patch': 869,
 'solemn': 870,
 'folks': 871,
 'event': 872,
 'slam': 873,
 'senate': 874,
 'greeting': 875,
 'derive': 876,
 'expose': 877,
 'uturn': 878,
 'circulates': 879,
 'edition': 880,
 'persist': 881,
 'again': 882,
 'majoring': 883,
 'idiotic': 884,
 'insensitive': 885,
 'forgiveness': 886,
 'freshen': 887,
 'teach': 888,
 'novelist': 889,
 'permanently': 890,
 'courses': 891,
 'lame': 892,
 'labor': 893,
 'waste': 894,
 'outstanding': 895,
 'hummingbird': 896,
 'herself': 897,
 'circus': 898,
 'tells': 899,
 'adjourn': 900,
 'motel': 901,
 'persuasive': 902,
 'secondbest': 903,
 'lasts': 904,
 'splinter': 905,
 'praising': 906,
 'determined': 907,
 'falsehood': 908,
 'drugs': 909,
 'answers': 910,
 'anchovies': 911,
 'soon': 912,
 'costumes': 913,
 'incident': 914,
 'celebrities': 915,
 'powerful': 916,
 'ninetynine': 917,
 "anybody's": 918,
 'sunday': 919,
 'net': 920,
 'registration': 921,
 'postponed': 922,
 'forbid': 923,
 'lucy': 924,
 'tinge': 925,
 "grandfather's": 926,
 'enlightened': 927,
 'effort': 928,
 'attacking': 929,
 'footing': 930,
 'aptitude': 931,
 'reconcile': 932,
 'four': 933,
 'prospects': 934,
 'chandelier': 935,
 "tony's": 936,
 'civilizations': 937,
 'revolutions': 938,
 'affected': 939,
 'introduces': 940,
 'degas': 941,
 'tyrant': 942,
 'diminished': 943,
 'slaughtered': 944,
 'chopin': 945,
 'conducive': 946,
 'counsel': 947,
 'unto': 948,
 'west': 949,
 'rooted': 950,
 'illgotten': 951,
 'illusion': 952,
 'balls': 953,
 'interpretation': 954,
 'lies': 955,
 'sentry': 956,
 'tatami': 957,
 'addictive': 958,
 'guilt': 959,
 'houses': 960,
 'unanimous': 961,
 'desk': 962,
 'hitler': 963,
 'drugstore': 964,
 'cheque': 965,
 'disclose': 966,
 'surpasses': 967,
 'uyghur': 968,
 'occurred': 969,
 'shortlived': 970,
 'wealth': 971,
 'canvas': 972,
 'twenties': 973,
 'presently': 974,
 'industries': 975,
 'radiation': 976,
 'policemen': 977,
 'are': 978,
 'remaining': 979,
 'needles': 980,
 'swarm': 981,
 'opening': 982,
 'requires': 983,
 "darwin's": 984,
 'sweeping': 985,
 "week's": 986,
 'fled': 987,
 'celebrated': 988,
 'brothers': 989,
 'knack': 990,
 'became': 991,
 'complicated': 992,
 'brochure': 993,
 'finer': 994,
 'accidents': 995,
 'dough': 996,
 'fullest': 997,
 'magnificent': 998,
 'gums': 999,
 ...}

In [12]:
# Claude improved my function btw. I 100% knows how does it work!
def create_dataset(sentence, stoi):
    X, Y = [], []
    sentence = ["<pad>", "<pad>"] + sentence.split() + ["<pad>", "<pad>"]
    UNK = stoi["<unk>"]
    for i in range(2, len(sentence) - 2):
        context = [stoi.get(sentence[j], UNK) for j in (i-2, i-1, i+1, i+2)]
        target = stoi.get(sentence[i], UNK)
        X.append(context)
        Y.append(target)
    return X, Y

X, Y = [], []
for s in sentences:
    xs, ys = create_dataset(s, stoi)
    X.extend(xs)
    Y.extend(ys)

In [13]:
X

[[0, 0, 9343, 12587],
 [0, 8612, 12587, 3562],
 [8612, 9343, 3562, 12587],
 [9343, 12587, 12587, 7254],
 [12587, 3562, 7254, 0],
 [3562, 12587, 0, 0],
 [0, 0, 13763, 1569],
 [0, 8255, 1569, 1723],
 [8255, 13763, 1723, 11937],
 [13763, 1569, 11937, 4667],
 [1569, 1723, 4667, 13763],
 [1723, 11937, 13763, 2278],
 [11937, 4667, 2278, 5820],
 [4667, 13763, 5820, 0],
 [13763, 2278, 0, 0],
 [0, 0, 13763, 6416],
 [0, 6415, 6416, 0],
 [6415, 13763, 0, 0],
 [0, 0, 4542, 13763],
 [0, 12503, 13763, 6415],
 [12503, 4542, 6415, 0],
 [4542, 13763, 0, 0],
 [0, 0, 10239, 5461],
 [0, 8612, 5461, 8916],
 [8612, 10239, 8916, 912],
 [10239, 5461, 912, 0],
 [5461, 8916, 0, 0],
 [0, 0, 81, 8173],
 [0, 5160, 8173, 365],
 [5160, 81, 365, 10397],
 [81, 8173, 10397, 145],
 [8173, 365, 145, 0],
 [365, 10397, 0, 0],
 [0, 0, 13763, 12718],
 [0, 4787, 12718, 1003],
 [4787, 13763, 1003, 12587],
 [13763, 12718, 12587, 10036],
 [12718, 1003, 10036, 0],
 [1003, 12587, 0, 0],
 [0, 0, 310, 9993],
 [0, 8612, 9993, 8536],
 [8612, 310, 8536, 12963],
 [310, 9993, 12963, 12587],
 [9993, 8536, 12587, 11435],
 [8536, 12963, 11435, 0],
 [12963, 12587, 0, 0],
 [0, 0, 13327, 8951],
 [0, 13634, 8951, 9074],
 [13634, 13327, 9074, 1],
 [13327, 8951, 1, 0],
 [8951, 9074, 0, 0],
 [0, 0, 13327, 8748],
 [0, 8612, 8748, 12503],
 [8612, 13327, 12503, 6411],
 [13327, 8748, 6411, 0],
 [8748, 12503, 0, 0],
 [0, 0, 4667, 8173],
 [0, 13763, 8173, 1609],
 [13763, 4667, 1609, 2662],
 [4667, 8173, 2662, 0],
 [8173, 1609, 0, 0],
 [0, 0, 9993, 8536],
 [0, 8612, 8536, 1693],
 [8612, 9993, 1693, 8612],
 [9993, 8536, 8612, 9343],
 [8536, 1693, 9343, 12503],
 [1693, 8612, 12503, 12748],
 [8612, 9343, 12748, 0],
 [9343, 12503, 0, 0],
 [0, 0, 8748, 4787],
 [0, 9435, 4787, 2274],
 [9435, 8748, 2274, 1],
 [8748, 4787, 1, 13120],
 [4787, 2274, 13120, 0],
 [2274, 1, 0, 0],
 [0, 0, 8748, 2444],
 [0, 6531, 2444, 2546],
 [6531, 8748, 2546, 10255],
 [8748, 2444, 10255, 8612],
 [2444, 2546, 8612, 2096],
 [2546, 10255, 2096, 0],
 [10255, 8612, 0, 0],
 [0, 0, 978, 8748],
 [0, 3677, 8748, 4236],
 [3677, 978, 4236, 14042],
 [978, 8748, 14042, 0],
 [8748, 4236, 0, 0],
 [0, 0, 10239, 6617],
 [0, 4787, 6617, 0],
 [4787, 10239, 0, 0],
 [0, 0, 5712, 8173],
 [0, 8612, 8173, 290],
 [8612, 5712, 290, 0],
 [5712, 8173, 0, 0],
 [0, 0, 1902, 4533],
 [0, 8612, 4533, 12793],
 [8612, 1902, 12793, 912],
 [1902, 4533, 912, 11937],
 [4533, 12793, 11937, 310],
 [12793, 912, 310, 11137],
 [912, 11937, 11137, 2767],
 [11937, 310, 2767, 0],
 [310, 11137, 0, 0],
 [0, 0, 4612, 3677],
 [0, 12294, 3677, 9993],
 [12294, 4612, 9993, 13957],
 [4612, 3677, 13957, 12587],
 [3677, 9993, 12587, 5461],
 [9993, 13957, 5461, 4148],
 [13957, 12587, 4148, 0],
 [12587, 5461, 0, 0],
 [0, 0, 12212, 2178],
 [0, 13634, 2178, 0],
 [13634, 12212, 0, 0],
 [0, 0, 1894, 12035],
 [0, 8649, 12035, 5461],
 [8649, 1894, 5461, 8173],
 [1894, 12035, 8173, 281],
 [12035, 5461, 281, 3831],
 [5461, 8173, 3831, 0],
 [8173, 281, 0, 0],
 [0, 0, 6187, 4236],
 [0, 7636, 4236, 12671],
 [7636, 6187, 12671, 6513],
 [6187, 4236, 6513, 12587],
 [4236, 12671, 12587, 2214],
 [12671, 6513, 2214, 12318],
 [6513, 12587, 12318, 592],
 [12587, 2214, 592, 0],
 [2214, 12318, 0, 0],
 [0, 0, 12035, 1896],
 [0, 8612, 1896, 5448],
 [8612, 12035, 5448, 1693],
 [12035, 1896, 1693, 4787],
 [1896, 5448, 4787, 13763],
 [5448, 1693, 13763, 12503],
 [1693, 4787, 12503, 3836],
 [4787, 13763, 3836, 10397],
 [13763, 12503, 10397, 13148],
 [12503, 3836, 13148, 6863],
 [3836, 10397, 6863, 0],
 [10397, 13148, 0, 0],
 [0, 0, 8249, 12294],
 [0, 8612, 12294, 9384],
 [8612, 8249, 9384, 7294],
 [8249, 12294, 7294, 3677],
 [12294, 9384, 3677, 13108],
 [9384, 7294, 13108, 2734],
 [7294, 3677, 2734, 4667],
 [3677, 13108, 4667, 10554],
 [13108, 2734, 10554, 12503],
 [2734, 4667, 12503, 633],
 [4667, 10554, 633, 7893],
 [10554, 12503, 7893, 0],
 [12503, 633, 0, 0],
 [0, 0, 5605, 3677],
 [0, 8612, 3677, 0],
 [8612, 5605, 0, 0],
 [0, 0, 8831, 2305],
 [0, 7636, 2305, 11628],
 [7636, 8831, 11628, 7294],
 [8831, 2305, 7294, 8612],
 [2305, 11628, 8612, 8598],
 [11628, 7294, 8598, 8916],
 [7294, 8612, 8916, 0],
 [8612, 8598, 0, 0],
 [0, 0, 3479, 4532],
 [0, 8612, 4532, 7885],
 [8612, 3479, 7885, 2422],
 [3479, 4532, 2422, 2398],
 [4532, 7885, 2398, 0],
 [7885, 2422, 0, 0],
 [0, 0, 7004, 7254],
 [0, 3677, 7254, 0],
 [3677, 7004, 0, 0],
 [0, 0, 1003, 12587],
 [0, 5160, 12587, 3562],
 [5160, 1003, 3562, 0],
 [1003, 12587, 0, 0],
 [0, 0, 8442, 2305],
 [0, 8612, 2305, 12587],
 [8612, 8442, 12587, 9339],
 [8442, 2305, 9339, 13120],
 [2305, 12587, 13120, 1469],
 [12587, 9339, 1469, 6185],
 [9339, 13120, 6185, 0],
 [13120, 1469, 0, 0],
 [0, 0, 3509, 5479],
 [0, 6531, 5479, 14001],
 [6531, 3509, 14001, 13120],
 [3509, 5479, 13120, 0],
 [5479, 14001, 0, 0],
 [0, 0, 8669, 12330],
 [0, 8612, 12330, 13634],
 [8612, 8669, 13634, 3448],
 [8669, 12330, 3448, 4780],
 [12330, 13634, 4780, 680],
 [13634, 3448, 680, 0],
 [3448, 4780, 0, 0],
 [0, 0, 3280, 5715],
 [0, 8612, 5715, 12587],
 [8612, 3280, 12587, 5461],
 [3280, 5715, 5461, 8951],
 [5715, 12587, 8951, 1],
 [12587, 5461, 1, 0],
 [5461, 8951, 0, 0],
 [0, 0, 12718, 4532],
 [0, 8612, 4532, 7614],
 [8612, 12718, 7614, 0],
 [12718, 4532, 0, 0],
 [0, 0, 3783, 4696],
 [0, 12503, 4696, 8612],
 [12503, 3783, 8612, 8442],
 [3783, 4696, 8442, 4236],
 [4696, 8612, 4236, 4134],
 [8612, 8442, 4134, 12587],
 [8442, 4236, 12587, 2135],
 [4236, 4134, 2135, 8612],
 [4134, 12587, 8612, 13327],
 [12587, 2135, 13327, 2172],
 [2135, 8612, 2172, 0],
 [8612, 13327, 0, 0],
 [0, 0, 12503, 2274],
 [0, 1693, 2274, 11431],
 [1693, 12503, 11431, 8748],
 [12503, 2274, 8748, 12503],
 [2274, 11431, 12503, 2546],
 [11431, 8748, 2546, 4667],
 [8748, 12503, 4667, 13763],
 [12503, 2546, 13763, 6416],
 [2546, 4667, 6416, 8612],
 [4667, 13763, 8612, 11286],
 [13763, 6416, 11286, 9890],
 [6416, 8612, 9890, 8742],
 [8612, 11286, 8742, 0],
 [11286, 9890, 0, 0],
 [0, 0, 13763, 4197],
 [0, 4667, 4197, 12849],
 [4667, 13763, 12849, 0],
 [13763, 4197, 0, 0],
 [0, 0, 978, 9945],
 [0, 8970, 9945, 1553],
 [8970, 978, 1553, 7678],
 [978, 9945, 7678, 3795],
 [9945, 1553, 3795, 4730],
 [1553, 7678, 4730, 10985],
 [7678, 3795, 10985, 12587],
 [3795, 4730, 12587, 6528],
 [4730, 10985, 6528, 10397],
 [10985, 12587, 10397, 3627],
 [12587, 6528, 3627, 2402],
 [6528, 10397, 2402, 0],
 [10397, 3627, 0, 0],
 [0, 0, 4285, 13108],
 [0, 4691, 13108, 5160],
 [4691, 4285, 5160, 6556],
 [4285, 13108, 6556, 0],
 [13108, 5160, 0, 0],
 [0, 0, 5160, 6513],
 [0, 7260, 6513, 3677],
 [7260, 5160, 3677, 978],
 [5160, 6513, 978, 0],
 [6513, 3677, 0, 0],
 [0, 0, 4236, 8987],
 [0, 7142, 8987, 0],
 [7142, 4236, 0, 0],
 [0, 0, 7383, 13120],
 [0, 5176, 13120, 0],
 [5176, 7383, 0, 0],
 [0, 0, 3677, 6791],
 [0, 978, 6791, 0],
 [978, 3677, 0, 0],
 [0, 0, 11270, 13763],
 [0, 13140, 13763, 8173],
 [13140, 11270, 8173, 11370],
 [11270, 13763, 11370, 0],
 [13763, 8173, 0, 0],
 [0, 0, 3180, 8173],
 [0, 12474, 8173, 11276],
 [12474, 3180, 11276, 0],
 [3180, 8173, 0, 0],
 [0, 0, 12793, 0],
 [0, 7523, 0, 0],
 [0, 0, 7985, 13890],
 [0, 4667, 13890, 13120],
 [4667, 7985, 13120, 0],
 [7985, 13890, 0, 0],
 [0, 0, 6137, 11142],
 [0, 10397, 11142, 8612],
 [10397, 6137, 8612, 1089],
 [6137, 11142, 1089, 2398],
 [11142, 8612, 2398, 6112],
 [8612, 1089, 6112, 81],
 [1089, 2398, 81, 3194],
 [2398, 6112, 3194, 0],
 [6112, 81, 0, 0],
 [0, 0, 10292, 9276],
 [0, 4667, 9276, 12503],
 [4667, 10292, 12503, 9522],
 [10292, 9276, 9522, 0],
 [9276, 12503, 0, 0],
 [0, 0, 3677, 14071],
 [0, 978, 14071, 9040],
 [978, 3677, 9040, 13120],
 [3677, 14071, 13120, 0],
 [14071, 9040, 0, 0],
 [0, 0, 12503, 1],
 [0, 7142, 1, 10733],
 [7142, 12503, 10733, 13292],
 [12503, 1, 13292, 2821],
 [1, 10733, 2821, 3318],
 [10733, 13292, 3318, 0],
 [13292, 2821, 0, 0],
 [0, 0, 9993, 13957],
 [0, 8612, 13957, 12587],
 [8612, 9993, 12587, 5461],
 [9993, 13957, 5461, 892],
 [13957, 12587, 892, 8612],
 [12587, 5461, 8612, 13957],
 [5461, 892, 13957, 12587],
 [892, 8612, 12587, 5461],
 [8612, 13957, 5461, 1856],
 [13957, 12587, 1856, 0],
 [12587, 5461, 0, 0],
 [0, 0, 8612, 13738],
 [0, 7294, 13738, 12793],
 [7294, 8612, 12793, 8612],
 [8612, 13738, 8612, 13957],
 [13738, 12793, 13957, 12587],
 [12793, 8612, 12587, 5461],
 [8612, 13957, 5461, 8173],
 [13957, 12587, 8173, 9178],
 [12587, 5461, 9178, 0],
 [5461, 8173, 0, 0],
 [0, 0, 13763, 8173],
 [0, 5480, 8173, 6001],
 [5480, 13763, 6001, 3068],
 [13763, 8173, 3068, 12587],
 [8173, 6001, 12587, 5461],
 [6001, 3068, 5461, 1693],
 [3068, 12587, 1693, 3677],
 [12587, 5461, 3677, 978],
 [5461, 1693, 978, 11481],
 [1693, 3677, 11481, 12587],
 [3677, 978, 12587, 5252],
 [978, 11481, 5252, 12904],
 [11481, 12587, 12904, 0],
 [12587, 5252, 0, 0],
 [0, 0, 3509, 6840],
 [0, 5160, 6840, 0],
 [5160, 3509, 0, 0],
 [0, 0, 12963, 0],
 [0, 3509, 0, 0],
 [0, 0, 9830, 7725],
 [0, 5160, 7725, 9631],
 [5160, 9830, 9631, 0],
 [9830, 7725, 0, 0],
 [0, 0, 6513, 8173],
 [0, 5160, 8173, 4437],
 [5160, 6513, 4437, 10666],
 [6513, 8173, 10666, 5160],
 [8173, 4437, 5160, 310],
 [4437, 10666, 310, 8173],
 [10666, 5160, 8173, 1923],
 [5160, 310, 1923, 1],
 [310, 8173, 1, 0],
 [8173, 1923, 0, 0],
 [0, 0, 310, 1145],
 [0, 5160, 1145, 0],
 [5160, 310, 0, 0],
 [0, 0, 13327, 12297],
 [0, 13634, 12297, 12963],
 [13634, 13327, 12963, 2778],
 [13327, 12297, 2778, 2851],
 [12297, 12963, 2851, 11177],
 [12963, 2778, 11177, 0],
 [2778, 2851, 0, 0],
 [0, 0, 3479, 9061],
 [0, 13292, 9061, 12963],
 [13292, 3479, 12963, 9289],
 [3479, 9061, 9289, 5461],
 [9061, 12963, 5461, 1493],
 [12963, 9289, 1493, 12587],
 [9289, 5461, 12587, 9343],
 [5461, 1493, 9343, 3622],
 [1493, 12587, 3622, 0],
 [12587, 9343, 0, 0],
 [0, 0, 13763, 12963],
 [0, 4787, 12963, 8612],
 [4787, 13763, 8612, 10303],
 [13763, 12963, 10303, 9343],
 [12963, 8612, 9343, 3318],
 [8612, 10303, 3318, 0],
 [10303, 9343, 0, 0],
 [0, 0, 10303, 12494],
 [0, 4667, 12494, 8077],
 [4667, 10303, 8077, 10397],
 [10303, 12494, 10397, 13120],
 [12494, 8077, 13120, 12587],
 [8077, 10397, 12587, 13355],
 [10397, 13120, 13355, 9808],
 [13120, 12587, 9808, 0],
 [12587, 13355, 0, 0],
 [0, 0, 4612, 6531],
 [0, 7142, 6531, 8173],
 [7142, 4612, 8173, 13506],
 [4612, 6531, 13506, 0],
 [6531, 8173, 0, 0],
 [0, 0, 8612, 8669],
 [0, 8649, 8669, 138],
 [8649, 8612, 138, 3629],
 [8612, 8669, 3629, 1901],
 [8669, 138, 1901, 0],
 [138, 3629, 0, 0],
 [0, 0, 8173, 8329],
 [0, 12294, 8329, 3589],
 [12294, 8173, 3589, 1493],
 [8173, 8329, 1493, 12587],
 [8329, 3589, 12587, 12415],
 [3589, 1493, 12415, 8173],
 [1493, 12587, 8173, 5022],
 [12587, 12415, 5022, 10397],
 [12415, 8173, 10397, 0],
 [8173, 5022, 0, 0],
 [0, 0, 10303, 5461],
 [0, 4667, 5461, 12287],
 [4667, 10303, 12287, 3589],
 [10303, 5461, 3589, 9343],
 [5461, 12287, 9343, 12587],
 [12287, 3589, 12587, 11410],
 [3589, 9343, 11410, 0],
 [9343, 12587, 0, 0],
 [0, 0, 9993, 5694],
 [0, 8612, 5694, 12587],
 [8612, 9993, 12587, 5461],
 [9993, 5694, 5461, 9909],
 [5694, 12587, 9909, 0],
 [12587, 5461, 0, 0],
 [0, 0, 6953, 12503],
 [0, 2007, 12503, 9496],
 [2007, 6953, 9496, 13634],
 [6953, 12503, 13634, 11286],
 [12503, 9496, 11286, 2178],
 [9496, 13634, 2178, 0],
 [13634, 11286, 0, 0],
 [0, 0, 4061, 10805],
 [0, 3214, 10805, 2494],
 [3214, 4061, 2494, 6187],
 [4061, 10805, 6187, 3677],
 [10805, 2494, 3677, 9343],
 [2494, 6187, 9343, 0],
 [6187, 3677, 0, 0],
 [0, 0, 1902, 5461],
 [0, 8612, 5461, 5904],
 [8612, 1902, 5904, 9787],
 [1902, 5461, 9787, 4667],
 [5461, 5904, 4667, 7985],
 [5904, 9787, 7985, 1416],
 [9787, 4667, 1416, 8612],
 [4667, 7985, 8612, 9993],
 [7985, 1416, 9993, 4005],
 [1416, 8612, 4005, 12587],
 [8612, 9993, 12587, 4285],
 [9993, 4005, 4285, 0],
 [4005, 12587, 0, 0],
 [0, 0, 13763, 3479],
 [0, 4787, 3479, 12503],
 [4787, 13763, 12503, 14042],
 [13763, 3479, 14042, 4667],
 [3479, 12503, 4667, 6335],
 [12503, 14042, 6335, 3828],
 [14042, 4667, 3828, 0],
 [4667, 6335, 0, 0],
 [0, 0, 13108, 4667],
 [0, 8612, 4667, 13763],
 [8612, 13108, 13763, 12671],
 [13108, 4667, 12671, 6513],
 [4667, 13763, 6513, 12587],
 [13763, 12671, 12587, 5461],
 [12671, 6513, 5461, 11718],
 [6513, 12587, 11718, 0],
 [12587, 5461, 0, 0],
 [0, 0, 12035, 3479],
 [0, 12317, 3479, 12415],
 [12317, 12035, 12415, 12748],
 [12035, 3479, 12748, 0],
 [3479, 12415, 0, 0],
 [0, 0, 5461, 4549],
 [0, 3589, 4549, 9787],
 [3589, 5461, 9787, 8612],
 [5461, 4549, 8612, 9521],
 [4549, 9787, 9521, 4808],
 [9787, 8612, 4808, 12780],
 [8612, 9521, 12780, 0],
 [9521, 4808, 0, 0],
 [0, 0, 8748, 13389],
 [0, 8916, 13389, 1307],
 [8916, 8748, 1307, 8612],
 [8748, 13389, 8612, 12912],
 [13389, 1307, 12912, 12793],
 [1307, 8612, 12793, 81],
 [8612, 12912, 81, 2096],
 [12912, 12793, 2096, 3368],
 [12793, 81, 3368, 5254],
 [81, 2096, 5254, 0],
 [2096, 3368, 0, 0],
 [0, 0, 8612, 3537],
 [0, 7294, 3537, 12793],
 [7294, 8612, 12793, 8612],
 [8612, 3537, 8612, 13327],
 [3537, 12793, 13327, 2839],
 [12793, 8612, 2839, 0],
 [8612, 13327, 0, 0],
 [0, 0, 13763, 10966],
 [0, 13634, 10966, 11743],
 [13634, 13763, 11743, 81],
 [13763, 10966, 81, 12503],
 [10966, 11743, 12503, 10036],
 [11743, 81, 10036, 0],
 [81, 12503, 0, 0],
 [0, 0, 2135, 3677],
 [0, 8612, 3677, 4532],
 [8612, 2135, 4532, 12587],
 [2135, 3677, 12587, 782],
 [3677, 4532, 782, 1826],
 [4532, 12587, 1826, 9438],
 [12587, 782, 9438, 0],
 [782, 1826, 0, 0],
 [0, 0, 4285, 9028],
 [0, 4691, 9028, 2734],
 [4691, 4285, 2734, 2851],
 [4285, 9028, 2851, 4454],
 [9028, 2734, 4454, 680],
 [2734, 2851, 680, 0],
 [2851, 4454, 0, 0],
 [0, 0, 8612, 11286],
 [0, 1693, 11286, 9339],
 [1693, 8612, 9339, 3677],
 [8612, 11286, 3677, 8173],
 [11286, 9339, 8173, 1],
 [9339, 3677, 1, 6641],
 [3677, 8173, 6641, 8612],
 [8173, 1, 8612, 10303],
 [1, 6641, 10303, 0],
 [6641, 8612, 0, 0],
 [0, 0, 12721, 12587],
 [0, 8748, 12587, 6187],
 [8748, 12721, 6187, 13634],
 [12721, 12587, 13634, 3677],
 [12587, 6187, 3677, 9343],
 [6187, 13634, 9343, 12587],
 [13634, 3677, 12587, 12494],
 [3677, 9343, 12494, 1783],
 [9343, 12587, 1783, 0],
 [12587, 12494, 0, 0],
 [0, 0, 4696, 6630],
 [0, 3368, 6630, 13763],
 [3368, 4696, 13763, 4148],
 [4696, 6630, 4148, 13763],
 [6630, 13763, 13763, 4148],
 [13763, 4148, 4148, 4612],
 [4148, 13763, 4612, 8970],
 [13763, 4148, 8970, 978],
 [4148, 4612, 978, 2594],
 [4612, 8970, 2594, 4780],
 [8970, 978, 4780, 11206],
 [978, 2594, 11206, 0],
 [2594, 4780, 0, 0],
 [0, 0, 6187, 3677],
 [0, 7420, 3677, 6036],
 [7420, 6187, 6036, 0],
 [6187, 3677, 0, 0],
 [0, 0, 2096, 6513],
 [0, 8612, 6513, 8951],
 [8612, 2096, 8951, 11987],
 [2096, 6513, 11987, 8612],
 [6513, 8951, 8612, 12718],
 [8951, 11987, 12718, 2760],
 [11987, 8612, 2760, 12503],
 [8612, 12718, 12503, 990],
 [12718, 2760, 990, 10397],
 [2760, 12503, 10397, 4667],
 [12503, 990, 4667, 0],
 [990, 10397, 0, 0],
 [0, 0, 8669, 2800],
 [0, 8612, 2800, 7146],
 [8612, 8669, 7146, 6416],
 [8669, 2800, 6416, 12294],
 [2800, 7146, 12294, 6513],
 [7146, 6416, 6513, 13634],
 [6416, 12294, 13634, 10698],
 [12294, 6513, 10698, 7628],
 [6513, 13634, 7628, 0],
 [13634, 10698, 0, 0],
 [0, 0, 2096, 8173],
 [0, 8612, 8173, 1],
 [8612, 2096, 1, 4696],
 [2096, 8173, 4696, 9787],
 [8173, 1, 9787, 2943],
 [1, 4696, 2943, 978],
 [4696, 9787, 978, 3935],
 [9787, 2943, 3935, 13634],
 [2943, 978, 13634, 12035],
 [978, 3935, 12035, 132],
 [3935, 13634, 132, 5461],
 [13634, 12035, 5461, 612],
 [12035, 132, 612, 0],
 [132, 5461, 0, 0],
 [0, 0, 8612, 12415],
 [0, 13765, 12415, 12287],
 [13765, 8612, 12287, 8612],
 [8612, 12415, 8612, 1493],
 [12415, 12287, 1493, 12294],
 [12287, 8612, 12294, 9945],
 [8612, 1493, 9945, 9130],
 [1493, 12294, 9130, 0],
 [12294, 9945, 0, 0],
 [0, 0, 633, 11421],
 [0, 3214, 11421, 3677],
 [3214, 633, 3677, 11621],
 [633, 11421, 11621, 0],
 [11421, 3677, 0, 0],
 [0, 0, 4667, 10239],
 [0, 4043, 10239, 5461],
 [4043, 4667, 5461, 4903],
 [4667, 10239, 4903, 12503],
 [10239, 5461, 12503, 3836],
 [5461, 4903, 3836, 10397],
 [4903, 12503, 10397, 9631],
 [12503, 3836, 9631, 0],
 [3836, 10397, 0, 0],
 [0, 0, 13763, 8173],
 [0, 597, 8173, 13914],
 [597, 13763, 13914, 10733],
 [13763, 8173, 10733, 0],
 [8173, 13914, 0, 0],
 [0, 0, 8116, 12718],
 [0, 9019, 12718, 5345],
 [9019, 8116, 5345, 12587],
 [8116, 12718, 12587, 12330],
 [12718, 5345, 12330, 8077],
 [5345, 12587, 8077, 0],
 [12587, 12330, 0, 0],
 [0, 0, 9993, 13957],
 [0, 8612, 13957, 12587],
 [8612, 9993, 12587, 11729],
 [9993, 13957, 11729, 4236],
 [13957, 12587, 4236, 8092],
 [12587, 11729, 8092, 11846],
 [11729, 4236, 11846, 3603],
 [4236, 8092, 3603, 6137],
 [8092, 11846, 6137, 4780],
 [11846, 3603, 4780, 2305],
 [3603, 6137, 2305, 978],
 [6137, 4780, 978, 8173],
 [4780, 2305, 8173, 10801],
 [2305, 978, 10801, 7117],
 [978, 8173, 7117, 0],
 [8173, 10801, 0, 0],
 [0, 0, 13108, 8612],
 [0, 8612, 8612, 9343],
 [8612, 13108, 9343, 8173],
 [13108, 8612, 8173, 3378],
 [8612, 9343, 3378, 2734],
 [9343, 8173, 2734, 13634],
 [8173, 3378, 13634, 0],
 [3378, 2734, 0, 0],
 [0, 0, 13763, 2696],
 [0, 13634, 2696, 0],
 [13634, 13763, 0, 0],
 [0, 0, 978, 1145],
 [0, 3677, 1145, 3677],
 [3677, 978, 3677, 9823],
 [978, 1145, 9823, 1773],
 [1145, 3677, 1773, 12318],
 [3677, 9823, 12318, 13279],
 [9823, 1773, 13279, 4716],
 [1773, 12318, 4716, 0],
 [12318, 13279, 0, 0],
 [0, 0, 6187, 6513],
 [0, 8612, 6513, 9343],
 [8612, 6187, 9343, 8951],
 [6187, 6513, 8951, 3095],
 [6513, 9343, 3095, 8748],
 [9343, 8951, 8748, 2943],
 [8951, 3095, 2943, 1],
 [3095, 8748, 1, 0],
 [8748, 2943, 0, 0],
 [0, 0, 8742, 13327],
 [0, 1693, 13327, 12587],
 [1693, 8742, 12587, 6036],
 [8742, 13327, 6036, 12963],
 [13327, 12587, 12963, 12503],
 [12587, 6036, 12503, 4311],
 [6036, 12963, 4311, 4780],
 [12963, 12503, 4780, 12503],
 [12503, 4311, 12503, 7153],
 [4311, 4780, 7153, 13763],
 [4780, 12503, 13763, 8612],
 [12503, 7153, 8612, 6957],
 [7153, 13763, 6957, 9993],
 [13763, 8612, 9993, 8536],
 [8612, 6957, 8536, 0],
 [6957, 9993, 0, 0],
 [0, 0, 8890, 8536],
 [0, 8612, 8536, 10839],
 [8612, 8890, 10839, 4667],
 [8890, 8536, 4667, 11097],
 [8536, 10839, 11097, 4635],
 [10839, 4667, 4635, 0],
 [4667, 11097, 0, 0],
 [0, 0, 13108, 4236],
 [0, 8612, 4236, 13157],
 [8612, 13108, 13157, 14001],
 [13108, 4236, 14001, 3677],
 [4236, 13157, 3677, 6335],
 [13157, 14001, 6335, 2778],
 [14001, 3677, 2778, 12318],
 [3677, 6335, 12318, 14042],
 [6335, 2778, 14042, 4780],
 [2778, 12318, 4780, 13157],
 [12318, 14042, 13157, 0],
 [14042, 4780, 0, 0],
 [0, 0, 13763, 6513],
 [0, 4787, 6513, 1285],
 [4787, 13763, 1285, 0],
 [13763, 6513, 0, 0],
 [0, 0, 8890, 1493],
 [0, 8612, 1493, 4667],
 [8612, 8890, 4667, 0],
 [8890, 1493, 0, 0],
 [0, 0, 7231, 3214],
 [0, 13305, 3214, 7142],
 [13305, 7231, 7142, 6674],
 [7231, 3214, 6674, 0],
 [3214, 7142, 0, 0],
 [0, 0, 310, 11241],
 [0, 6531, 11241, 12883],
 [6531, 310, 12883, 4635],
 [310, 11241, 4635, 2451],
 [11241, 12883, 2451, 211],
 [12883, 4635, 211, 0],
 [4635, 2451, 0, 0],
 [0, 0, 3677, 838],
 [0, 1693, 838, 81],
 [1693, 3677, 81, 12503],
 [3677, 838, 12503, 4350],
 [838, 81, 4350, 8970],
 [81, 12503, 8970, 9993],
 [12503, 4350, 9993, 6957],
 [4350, 8970, 6957, 1416],
 [8970, 9993, 1416, 12080],
 [9993, 6957, 12080, 0],
 [6957, 1416, 0, 0],
 [0, 0, 8173, 11370],
 [0, 3180, 11370, 11270],
 [3180, 8173, 11270, 13634],
 [8173, 11370, 13634, 3677],
 [11370, 11270, 3677, 9993],
 [11270, 13634, 9993, 1278],
 [13634, 3677, 1278, 0],
 [3677, 9993, 0, 0],
 [0, 0, 12035, 6187],
 [0, 3677, 6187, 4667],
 [3677, 12035, 4667, 0],
 [12035, 6187, 0, 0],
 [0, 0, 3879, 1512],
 [0, 4236, 1512, 7985],
 [4236, 3879, 7985, 6528],
 [3879, 1512, 6528, 1693],
 [1512, 7985, 1693, 8612],
 [7985, 6528, 8612, 823],
 [6528, 1693, 823, 6638],
 [1693, 8612, 6638, 0],
 [8612, 823, 0, 0],
 [0, 0, 8920, 8612],
 [0, 8612, 8612, 11286],
 [8612, 8920, 11286, 3562],
 [8920, 8612, 3562, 12587],
 [8612, 11286, 12587, 6135],
 [11286, 3562, 6135, 0],
 [3562, 12587, 0, 0],
 [0, 0, 1365, 4667],
 [0, 8612, 4667, 7294],
 [8612, 1365, 7294, 11270],
 [1365, 4667, 11270, 978],
 [4667, 7294, 978, 8173],
 [7294, 11270, 8173, 6736],
 [11270, 978, 6736, 4780],
 [978, 8173, 4780, 4285],
 [8173, 6736, 4285, 0],
 [6736, 4780, 0, 0],
 [0, 0, 9343, 12587],

In [14]:
Y

[8612,
 9343,
 12587,
 3562,
 12587,
 7254,
 8255,
 13763,
 1569,
 1723,
 11937,
 4667,
 13763,
 2278,
 5820,
 6415,
 13763,
 6416,
 12503,
 4542,
 13763,
 6415,
 8612,
 10239,
 5461,
 8916,
 912,
 5160,
 81,
 8173,
 365,
 10397,
 145,
 4787,
 13763,
 12718,
 1003,
 12587,
 10036,
 8612,
 310,
 9993,
 8536,
 12963,
 12587,
 11435,
 13634,
 13327,
 8951,
 9074,
 1,
 8612,
 13327,
 8748,
 12503,
 6411,
 13763,
 4667,
 8173,
 1609,
 2662,
 8612,
 9993,
 8536,
 1693,
 8612,
 9343,
 12503,
 12748,
 9435,
 8748,
 4787,
 2274,
 1,
 13120,
 6531,
 8748,
 2444,
 2546,
 10255,
 8612,
 2096,
 3677,
 978,
 8748,
 4236,
 14042,
 4787,
 10239,
 6617,
 8612,
 5712,
 8173,
 290,
 8612,
 1902,
 4533,
 12793,
 912,
 11937,
 310,
 11137,
 2767,
 12294,
 4612,
 3677,
 9993,
 13957,
 12587,
 5461,
 4148,
 13634,
 12212,
 2178,
 8649,
 1894,
 12035,
 5461,
 8173,
 281,
 3831,
 7636,
 6187,
 4236,
 12671,
 6513,
 12587,
 2214,
 12318,
 592,
 8612,
 12035,
 1896,
 5448,
 1693,
 4787,
 13763,
 12503,
 3836,
 10397,
 13148,
 6863,
 8612,
 8249,
 12294,
 9384,
 7294,
 3677,
 13108,
 2734,
 4667,
 10554,
 12503,
 633,
 7893,
 8612,
 5605,
 3677,
 7636,
 8831,
 2305,
 11628,
 7294,
 8612,
 8598,
 8916,
 8612,
 3479,
 4532,
 7885,
 2422,
 2398,
 3677,
 7004,
 7254,
 5160,
 1003,
 12587,
 3562,
 8612,
 8442,
 2305,
 12587,
 9339,
 13120,
 1469,
 6185,
 6531,
 3509,
 5479,
 14001,
 13120,
 8612,
 8669,
 12330,
 13634,
 3448,
 4780,
 680,
 8612,
 3280,
 5715,
 12587,
 5461,
 8951,
 1,
 8612,
 12718,
 4532,
 7614,
 12503,
 3783,
 4696,
 8612,
 8442,
 4236,
 4134,
 12587,
 2135,
 8612,
 13327,
 2172,
 1693,
 12503,
 2274,
 11431,
 8748,
 12503,
 2546,
 4667,
 13763,
 6416,
 8612,
 11286,
 9890,
 8742,
 4667,
 13763,
 4197,
 12849,
 8970,
 978,
 9945,
 1553,
 7678,
 3795,
 4730,
 10985,
 12587,
 6528,
 10397,
 3627,
 2402,
 4691,
 4285,
 13108,
 5160,
 6556,
 7260,
 5160,
 6513,
 3677,
 978,
 7142,
 4236,
 8987,
 5176,
 7383,
 13120,
 978,
 3677,
 6791,
 13140,
 11270,
 13763,
 8173,
 11370,
 12474,
 3180,
 8173,
 11276,
 7523,
 12793,
 4667,
 7985,
 13890,
 13120,
 10397,
 6137,
 11142,
 8612,
 1089,
 2398,
 6112,
 81,
 3194,
 4667,
 10292,
 9276,
 12503,
 9522,
 978,
 3677,
 14071,
 9040,
 13120,
 7142,
 12503,
 1,
 10733,
 13292,
 2821,
 3318,
 8612,
 9993,
 13957,
 12587,
 5461,
 892,
 8612,
 13957,
 12587,
 5461,
 1856,
 7294,
 8612,
 13738,
 12793,
 8612,
 13957,
 12587,
 5461,
 8173,
 9178,
 5480,
 13763,
 8173,
 6001,
 3068,
 12587,
 5461,
 1693,
 3677,
 978,
 11481,
 12587,
 5252,
 12904,
 5160,
 3509,
 6840,
 3509,
 12963,
 5160,
 9830,
 7725,
 9631,
 5160,
 6513,
 8173,
 4437,
 10666,
 5160,
 310,
 8173,
 1923,
 1,
 5160,
 310,
 1145,
 13634,
 13327,
 12297,
 12963,
 2778,
 2851,
 11177,
 13292,
 3479,
 9061,
 12963,
 9289,
 5461,
 1493,
 12587,
 9343,
 3622,
 4787,
 13763,
 12963,
 8612,
 10303,
 9343,
 3318,
 4667,
 10303,
 12494,
 8077,
 10397,
 13120,
 12587,
 13355,
 9808,
 7142,
 4612,
 6531,
 8173,
 13506,
 8649,
 8612,
 8669,
 138,
 3629,
 1901,
 12294,
 8173,
 8329,
 3589,
 1493,
 12587,
 12415,
 8173,
 5022,
 10397,
 4667,
 10303,
 5461,
 12287,
 3589,
 9343,
 12587,
 11410,
 8612,
 9993,
 5694,
 12587,
 5461,
 9909,
 2007,
 6953,
 12503,
 9496,
 13634,
 11286,
 2178,
 3214,
 4061,
 10805,
 2494,
 6187,
 3677,
 9343,
 8612,
 1902,
 5461,
 5904,
 9787,
 4667,
 7985,
 1416,
 8612,
 9993,
 4005,
 12587,
 4285,
 4787,
 13763,
 3479,
 12503,
 14042,
 4667,
 6335,
 3828,
 8612,
 13108,
 4667,
 13763,
 12671,
 6513,
 12587,
 5461,
 11718,
 12317,
 12035,
 3479,
 12415,
 12748,
 3589,
 5461,
 4549,
 9787,
 8612,
 9521,
 4808,
 12780,
 8916,
 8748,
 13389,
 1307,
 8612,
 12912,
 12793,
 81,
 2096,
 3368,
 5254,
 7294,
 8612,
 3537,
 12793,
 8612,
 13327,
 2839,
 13634,
 13763,
 10966,
 11743,
 81,
 12503,
 10036,
 8612,
 2135,
 3677,
 4532,
 12587,
 782,
 1826,
 9438,
 4691,
 4285,
 9028,
 2734,
 2851,
 4454,
 680,
 1693,
 8612,
 11286,
 9339,
 3677,
 8173,
 1,
 6641,
 8612,
 10303,
 8748,
 12721,
 12587,
 6187,
 13634,
 3677,
 9343,
 12587,
 12494,
 1783,
 3368,
 4696,
 6630,
 13763,
 4148,
 13763,
 4148,
 4612,
 8970,
 978,
 2594,
 4780,
 11206,
 7420,
 6187,
 3677,
 6036,
 8612,
 2096,
 6513,
 8951,
 11987,
 8612,
 12718,
 2760,
 12503,
 990,
 10397,
 4667,
 8612,
 8669,
 2800,
 7146,
 6416,
 12294,
 6513,
 13634,
 10698,
 7628,
 8612,
 2096,
 8173,
 1,
 4696,
 9787,
 2943,
 978,
 3935,
 13634,
 12035,
 132,
 5461,
 612,
 13765,
 8612,
 12415,
 12287,
 8612,
 1493,
 12294,
 9945,
 9130,
 3214,
 633,
 11421,
 3677,
 11621,
 4043,
 4667,
 10239,
 5461,
 4903,
 12503,
 3836,
 10397,
 9631,
 597,
 13763,
 8173,
 13914,
 10733,
 9019,
 8116,
 12718,
 5345,
 12587,
 12330,
 8077,
 8612,
 9993,
 13957,
 12587,
 11729,
 4236,
 8092,
 11846,
 3603,
 6137,
 4780,
 2305,
 978,
 8173,
 10801,
 7117,
 8612,
 13108,
 8612,
 9343,
 8173,
 3378,
 2734,
 13634,
 13634,
 13763,
 2696,
 3677,
 978,
 1145,
 3677,
 9823,
 1773,
 12318,
 13279,
 4716,
 8612,
 6187,
 6513,
 9343,
 8951,
 3095,
 8748,
 2943,
 1,
 1693,
 8742,
 13327,
 12587,
 6036,
 12963,
 12503,
 4311,
 4780,
 12503,
 7153,
 13763,
 8612,
 6957,
 9993,
 8536,
 8612,
 8890,
 8536,
 10839,
 4667,
 11097,
 4635,
 8612,
 13108,
 4236,
 13157,
 14001,
 3677,
 6335,
 2778,
 12318,
 14042,
 4780,
 13157,
 4787,
 13763,
 6513,
 1285,
 8612,
 8890,
 1493,
 4667,
 13305,
 7231,
 3214,
 7142,
 6674,
 6531,
 310,
 11241,
 12883,
 4635,
 2451,
 211,
 1693,
 3677,
 838,
 81,
 12503,
 4350,
 8970,
 9993,
 6957,
 1416,
 12080,
 3180,
 8173,
 11370,
 11270,
 13634,
 3677,
 9993,
 1278,
 3677,
 12035,
 6187,
 4667,
 4236,
 3879,
 1512,
 7985,
 6528,
 1693,
 8612,
 823,
 6638,
 8612,
 8920,
 8612,
 11286,
 3562,
 12587,
 6135,
 8612,
 1365,
 4667,
 7294,
 11270,
 978,
 8173,
 6736,
 4780,
 4285,
 8612,
 9343,
 12587,
 3562,
 12587,
 3219,
 8107,
 13634,
 8612,
 690,
 9787,
 13140,
 8612,
 9760,
 13634,
 8612,
 11842,
 4236,
 10341,
 81,
 2851,
 12947,
 8612,
 12212,
 6036,
 3677,
 4062,
 6863,
 8255,
 4667,
 1902,
 8090,
 9357,
 410,
 11846,
 3603,
 1894,
 2952,
 5160,
 8972,
 2831,
 12503,
 2752,
 10239,
 5646,
 3677,
 12587,
 12415,
 12503,
 5572,
 12554,
 10397,
 1301,
 11743,
 12587,
 13120,
 81,
 3783,
 7420,
 4285,
 12494,
 13120,
 10397,
 8951,
 11151,
 13634,
 2941,
 4236,
 3259,
 12554,
 10397,
 12318,
 1435,
 10023,
 5160,
 6077,
 2429,
 1693,
 3677,
 8890,
 8536,
 13120,
 13634,
 14042,
 13140,
 3677,
 10161,
 8890,
 8536,
 13120,
 4667,
 11473,
 12734,
 13120,
 6513,
 12587,
 1278,
 3677,
 7001,
 10397,
 8173,
 714,
 290,
 8612,
 9993,
 8536,
 12963,
 3677,
 1416,
 4236,
 4366,
 6335,
 12912,
 12587,
 5461,
 5472,
 10397,
 12287,
 3677,
 5715,
 12587,
 2800,
 13120,
 2734,
 10024,
 6565,
 6416,
 12294,
 6957,
 2893,
 1693,
 8612,
 5715,
 12587,
 210,
 3677,
 8612,
 10303,
 2800,
 3677,
 12963,
 8612,
 602,
 2734,
 8173,
 12203,
 7349,
 10493,
 12317,
 8669,
 8565,
 9808,
 4635,
 153,
 11270,
 978,
 4061,
 145,
 13634,
 8612,
 9993,
 2034,
 8612,
 9993,
 1493,
 4667,
 7294,
 6842,
 6630,
 8536,
 12080,
 2398,
 10255,
 8612,
 6187,
 8669,
 13420,
 7996,
 1,
 6531,
 6957,
 6513,
 2450,
 8612,
 9722,
 12587,
 6036,
 3677,
 8173,
 7473,
 4335,
 8612,
 9993,
 8536,
 3214,
 12587,
 6306,
 4667,
 11523,
 12294,
 9945,
 8667,
 8612,
 9521,
 9343,
 2135,
 8612,
 10303,
 ...]

In [15]:
# Generated by Claude

import torch
from torch.utils.data import Dataset, DataLoader

class CBOWDataset(Dataset):
    def __init__(self, X, Y):
        self.X = torch.tensor(X, dtype=torch.long)
        self.Y = torch.tensor(Y, dtype=torch.long)
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]

dataset = CBOWDataset(X, Y)
loader = DataLoader(dataset, batch_size=256, shuffle=True)

In [16]:
# Generated by Claude

import torch.nn as nn
class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_dim, pad_idx):
        super().__init__()
        self.embeddings = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_idx)
        self.linear = nn.Linear(embed_dim, vocab_size)

    def forward(self, context):
        embeds = self.embeddings(context)
        avg = embeds.mean(dim=1)
        logits = self.linear(avg)
        return logits

In [31]:
# Walkthrough 1
embed = nn.Embedding(len(vocab_full), 4, padding_idx=stoi["<pad>"])
linear = nn.Linear(4, len(vocab_full))
embeds = embed(torch.tensor(X[0]))
embeds

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3278,  0.8168, -0.5890, -0.6669],
        [-0.7513,  1.1689, -0.6213,  2.9871]], grad_fn=<EmbeddingBackward0>)

In [32]:
# Walkthrough 2
avg = embeds.mean(dim=1)
avg

tensor([ 0.0000,  0.0000, -0.0278,  0.6958], grad_fn=<MeanBackward1>)

In [33]:
# Walkthrouhg 3
logits = linear(avg)
logits

tensor([ 0.3195, -0.2494, -0.2449,  ...,  0.1322, -0.1461, -0.1140],
       grad_fn=<ViewBackward0>)

In [34]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

VOCAB_SIZE = len(stoi)
EMBED_DIM = 100
PAD_IDX = stoi["<pad>"]
BATCH_SIZE = 256
EPOCHS = 10
LR = 0.01

In [35]:
model = CBOW(VOCAB_SIZE, EMBED_DIM, PAD_IDX).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

In [36]:
for epoch in range(EPOCHS):
    total_loss = 0.0
    for context, target in loader:
        context, target = context.to(device), target.to(device)

        optimizer.zero_grad()
        logits = model(context)
        loss = criterion(logits, target)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {avg_loss:.4f}")

Epoch 1/10, Loss: 5.1704
Epoch 2/10, Loss: 4.4842
Epoch 3/10, Loss: 4.2862
Epoch 4/10, Loss: 4.1902
Epoch 5/10, Loss: 4.1360
Epoch 6/10, Loss: 4.1011
Epoch 7/10, Loss: 4.0803
Epoch 8/10, Loss: 4.0632
Epoch 9/10, Loss: 4.0502
Epoch 10/10, Loss: 4.0414

In [44]:
logits = model(torch.tensor(X[1]).unsqueeze(0).to(device))
predicted_id = torch.argmax(logits, dim=1)
itos[predicted_id.item()]

'want'

In [42]:
for i in X[1]:
    print(itos[i])

<pad>
i
to
go

In [43]:
itos[Y[1]]

'have'